// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc246.2014robot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around. Stores all the "magic numbers"
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftDriveMotor1;
    public static SpeedController drivetrainLeftDriveMotor2;
    public static SpeedController drivetrainRightDriveMotor1;
    public static SpeedController drivetrainRightDriveMotor2;
    public static RobotDrive drivetrainDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftDriveMotor1 = new Victor(1, 1);
	LiveWindow.addActuator("Drivetrain", "LeftDriveMotor1", (Victor) drivetrainLeftDriveMotor1);
        
        drivetrainLeftDriveMotor2 = new Victor(1, 2);
	LiveWindow.addActuator("Drivetrain", "LeftDriveMotor2", (Victor) drivetrainLeftDriveMotor2);
        
        drivetrainRightDriveMotor1 = new Victor(1, 3);
	LiveWindow.addActuator("Drivetrain", "RightDriveMotor1", (Victor) drivetrainRightDriveMotor1);
        
        drivetrainRightDriveMotor2 = new Victor(1, 4);
	LiveWindow.addActuator("Drivetrain", "RightDriveMotor2", (Victor) drivetrainRightDriveMotor2);
        
        drivetrainDrive = new RobotDrive(drivetrainLeftDriveMotor1, drivetrainLeftDriveMotor2,
              drivetrainRightDriveMotor1, drivetrainRightDriveMotor2);
	
        drivetrainDrive.setSafetyEnabled(true);
        drivetrainDrive.setExpiration(0.1);
        drivetrainDrive.setSensitivity(0.5);
        drivetrainDrive.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
